.PHONY: all complex clean

all: 
	g++ -O2 -Wall -Wextra complex.cpp -o complex && ./complex > set.pbm

farmer:
	g++ -O2 -Wall farmer.c -o farmer

worker:
	g++ -O2 -Wall worker.c -o worker


clean:
	rm *.c
