.PHONY: all farmer worker clean

all: 
	g++ -O2 -Wall farmer.c -o farmer
	g++ -O2 -Wall worker.c -o worker

farmer:
	g++ -O2 -Wall farmer.c -o farmer

worker:
	g++ -O2 -Wall worker.c -o worker


clean:
	rm *.c
